apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: odoo:12.0
          imagePullPolicy: ""
          name: web
          ports:
            - containerPort: 8069
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: web-data
            - mountPath: /etc/odoo
              name: web-claim1
            - mountPath: /mnt/extra-addons
              name: web-claim2
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: web-data
        - name: web-claim1
          persistentVolumeClaim:
            claimName: web-claim1
        - name: web-claim2
          persistentVolumeClaim:
            claimName: web-claim2
status: {}
